# Generated by Django 5.0.1 on 2024-01-20 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Volobot_assignment', '0003_alter_student_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_name',
            field=models.ForeignKey(max_length=1, on_delete=django.db.models.deletion.CASCADE, to='app_Volobot_assignment.section'),
        ),
    ]
