# Generated by Django 5.0.1 on 2024-01-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Volobot_assignment', '0004_alter_section_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_name',
            field=models.CharField(max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='section_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_Volobot_assignment.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
